name: recipe_book_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_markdown: ^0.6.18+1


  cupertino_icons: ^1.0.8
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  http: ^1.2.1
  provider: ^6.1.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  firebase_auth_mocks: ^0.14.2


flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env




